from app.core.celery_app import celery_app
from app.db.session import SessionLocal
from app.models import database
from app.core.config import settings
from sqlalchemy import func
from datetime import datetime, timedelta
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
import matplotlib.pyplot as plt
import io
import os

@celery_app.task
def generate_daily_report_task(user_id: int):
    """
    Generates a daily report chart and emails it to the user.
    Simulates a long-running data processing job.
    """
    print(f"📊 Generating Daily Report for User {user_id}...")
    
    # Check if Email Config is set
    if not settings.smtp_user or not settings.smtp_password:
        print("⚠️ SMTP credentials not set. Skipping email report.")
        return "Skipped (No SMTP Config)"

    recipient = settings.emails_to_email
    if not recipient:
        print("⚠️ No recipient email set. Skipping.")
        return "Skipped (No Recipient)"

    db = SessionLocal()
    try:
        # 1. Fetch Data (Last 24 Hours)
        since = datetime.utcnow() - timedelta(days=1)
        
        sessions = db.query(database.Session).filter(
            database.Session.user_id == user_id,
            database.Session.started_at >= since
        ).all()
        
        if not sessions:
            print("No sessions found for today.")
            return "No Data"

        # 2. Aggregation (Simulate heavy processing)
        total_duration = 0
        total_slouch = 0
        total_good = 0
        
        for session in sessions:
            logs = db.query(database.PostureLog).filter(
                database.PostureLog.session_id == session.id
            ).all()
            
            for log in logs:
                # Simple count (approx 0.5s per log)
                if log.posture_status == 'SLOUCHING':
                    total_slouch += 0.5
                elif log.posture_status == 'GOOD':
                    total_good += 0.5
        
        total_duration = total_slouch + total_good
        if total_duration == 0:
            return "Insufficient Data"

        # 3. Generate Chart (Matplotlib)
        # Use a non-interactive backend to avoid GUI errors
        plt.switch_backend('Agg') 
        
        fig, ax = plt.subplots(figsize=(6, 4))
        categories = ['Good Posture', 'Slouching']
        values = [total_good / 60, total_slouch / 60] # In minutes
        colors = ['#4ade80', '#f87171'] # Green, Red
        
        bars = ax.bar(categories, values, color=colors)
        
        ax.set_ylabel('Duration (Minutes)')
        ax.set_title(f'Posture Summary ({datetime.now().strftime("%Y-%m-%d")})')
        
        # Add values on top
        for bar in bars:
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height,
                    f'{height:.1f} min',
                    ha='center', va='bottom')
        
        # Save to buffer
        img_buf = io.BytesIO()
        plt.savefig(img_buf, format='png')
        img_buf.seek(0)
        plt.close(fig)
        
        print("📈 Chart generated successfully.")

        # 4. Compose Email
        msg = MIMEMultipart('related')
        msg['Subject'] = f"Daily Posture Report - {datetime.now().strftime('%Y-%m-%d')}"
        msg['From'] = settings.emails_from_email
        msg['To'] = recipient

        # HTML Body
        html_content = f"""
        <html>
          <body>
            <h2>Your Daily Posture Summary</h2>
            <p>Here is your activity for the last 24 hours:</p>
            <ul>
                <li>Total Monitored Time: <b>{total_duration/60:.1f} min</b></li>
                <li>Good Posture: <b style="color:green">{total_good/60:.1f} min</b></li>
                <li>Slouching: <b style="color:red">{total_slouch/60:.1f} min</b></li>
            </ul>
            <p>Keep improving your stats!</p>
            <br>
            <img src="cid:chart_image" alt="Daily Chart" style="width:100%; max-width:600px;">
            <br>
            <p><small>Generated by Posture Monitor AI Worker</small></p>
          </body>
        </html>
        """
        msg.attach(MIMEText(html_content, 'html'))

        # Attach Image
        img = MIMEImage(img_buf.read())
        img.add_header('Content-ID', '<chart_image>')
        msg.attach(img)

        # 5. Send Email via Gmail SMTP
        print(f"📧 Sending email to {recipient}...")
        with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
            server.starttls()
            server.login(settings.smtp_user, settings.smtp_password)
            server.send_message(msg)
            
        print("✅ Report sent successfully!")
        return "Sent"

    except Exception as e:
        print(f"✗ Report generation failed: {e}")
        return f"Failed: {e}"
    finally:
        db.close()
